project:
  type: website
  render:
    - quarto/index.qmd
    - quarto/report.qmd
    - quarto/run_for_station.qmd
  output-dir: ../rankings_website/
  
website: 
  navbar:
    title: 'Train Station Upzoning Priorities - YIMBY Melbourne'
    pinned: true
    search: false




    