project:
  type: website
  render:
    - quarto/index.qmd
  output-dir: ../rankings_website/
  
website: 
  navbar:
    title: 'The Next 25 - YIMBY Melbourne'
    pinned: true
    search: false
    



    