existing_upzoned_stations <- c(
  'Tottenham',
  'West Footscray',
  'Middle Footscray',
  'Blackburn',
  'Nunawading',
  'Mitcham',
  'Hawthorn',
  'Glenferrie',
  'Auburn',
  'Tooronga',
  'Glen Iris',
  'Darling',
  'Toorak Village',
  'Hawksburn',
  'Toorak',
  'Armadale',
  'Malvern',
  'Murrumbeena',
  'Hughesdale',
  'Oakleigh',
  'North Brighton',
  'Middle Brighton',
  'Hampton',
  'Sandringham',
  'Carnegie'
)

other_existing_precincts <- c(
  'Footscray',
  'Arden',
  'Box Hill',
  'Glen Waverley',
  'Clayton',
  'Richmond',
  'Sunshine',
  'East Werribee',
  'Dandenong',
  'Cheltenham',
  'Broadmeadows',
  'Frankston',
  'Camberwell',
  'Ringwood',
  'Preston',
  'Epping'
)